name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Semantic release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
